# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-12 01:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=150)),
                ('email', models.EmailField(default='', max_length=150)),
                ('password', models.CharField(default='', max_length=50)),
                ('firstname', models.CharField(default='', max_length=100)),
                ('lastname', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('discipline', models.CharField(default='', max_length=100)),
                ('hobbies', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
