# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 16:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_auto_20170705_2305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='music',
        ),
    ]
