# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-06 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_remove_user_music'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='discipline',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.TextField(default=''),
        ),
    ]
