# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-07-07 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0009_auto_20170707_0108'),
        ('registration', '0008_auto_20170707_0127'),
    ]

    operations = [
    ]
